export { default as Home } from "./Home"
export { default as Space } from "./Space"
export { default as Dropdown } from "./Dropdown"
export { default as Word } from "./Word"
export { default as AddModal} from "./AddModal"
export { default as NoMatch} from "./NoMatch"