export { default as Home } from "./Home"
export { default as Space } from "./Space"
export { default as Word } from "./Word"
export { default as AddModal } from "./AddModal"
export { default as Search } from "./Search"
export { default as Dictionary } from "./Dictionary"
export { default as List } from "./styled/List"
export { default as Navigation } from "./styled/Navigation"